package bootstrap

import (
	"fmt"
	"os"
	"strings"
)

// WriteComposeFile renders Mode B compose YAML and atomically writes it
// to path (tmp + rename). The shape matches `installer/install.sh`'s
// Mode B output — same service names, same volume mounts, same env
// vars — so existing update + selfupdate flows work unchanged on a
// bootstrap-first install.
//
// If path already exists, returns an error: bootstrap should never
// silently overwrite operator config. Skip-checks in Run guard against
// this in the happy path.
func WriteComposeFile(path string, p ComposeParams) error {
	if p.MainImage == "" || p.MainService == "" {
		return fmt.Errorf("WriteComposeFile: empty MainImage or MainService")
	}
	if p.UpdaterImage == "" {
		return fmt.Errorf("WriteComposeFile: empty UpdaterImage")
	}
	if p.UpdaterService == "" {
		p.UpdaterService = "clubfoundry-updater"
	}
	if p.HostDataDir == "" {
		p.HostDataDir = "/opt/clubfoundry/data"
	}
	if p.HostComposeFile == "" {
		p.HostComposeFile = "/opt/clubfoundry/docker-compose.yml"
	}
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("WriteComposeFile: %s already exists — refusing to overwrite", path)
	}

	body := strings.ReplaceAll(composeTemplate, "{{MAIN_IMAGE}}", p.MainImage)
	body = strings.ReplaceAll(body, "{{MAIN_SERVICE}}", p.MainService)
	body = strings.ReplaceAll(body, "{{UPDATER_IMAGE}}", p.UpdaterImage)
	body = strings.ReplaceAll(body, "{{UPDATER_SERVICE}}", p.UpdaterService)
	body = strings.ReplaceAll(body, "{{HOST_DATA_DIR}}", p.HostDataDir)
	body = strings.ReplaceAll(body, "{{HOST_COMPOSE_FILE}}", p.HostComposeFile)
	body = strings.ReplaceAll(body, "{{CLOUD_URL}}", p.CloudURL)

	return atomicWrite(path, []byte(body), 0o644)
}

// composeTemplate mirrors installer/install.sh's Mode B output. Two
// services — main + sidecar. Both use host networking so the main app's
// :3000 and the sidecar's :3001 are on the host's network namespace
// without port mapping.
//
// Why host networking on the sidecar (vs the existing bridge + 127.0.0.1
// port-map convention): on a fresh bootstrap-first install the sidecar
// must reach :3000 to verify main came up. Bridge → host gateway needs
// `--add-host=host.docker.internal:host-gateway` which is Linux-distro
// dependent. Host networking makes the probe trivial; sidecar's :3001
// listener is bound to 127.0.0.1 explicitly via CLUBFOUNDRY_UPDATER_ADDR,
// so it's not externally reachable.
const composeTemplate = `# ClubFoundry — Mode B (with updater sidecar).
# Generated by sidecar bootstrap. Edit manually to customize; the
# bootstrap NEVER overwrites this file (skip-check at startup).

# Project name anchor (Docker Compose v2.4+). Without this, compose
# derives the project name from the basename of CWD which differs
# between the sidecar (CWD=/app inside container) and the trampoline
# (CWD=/var/lib/clubfoundry on host). That drift produces two separate
# projects pointing at the same YAML; ` + "`compose ps`" + ` from one
# project misses services owned by the other → CurrentVersion returns
# "unknown" in history. Anchoring ` + "`name:`" + ` forces single-project
# topology regardless of CWD.
name: clubfoundry

services:
  {{MAIN_SERVICE}}:
    image: {{MAIN_IMAGE}}
    container_name: {{MAIN_SERVICE}}
    network_mode: host
    restart: unless-stopped
    # env_file is resolved relative to this compose file's dir. ./data/.env
    # works both from the host (/opt/clubfoundry/data/.env) and from inside
    # the sidecar (/app/data/.env via the data-dir bind mount), so the
    # sidecar can run docker compose without mirror-mounting an absolute path.
    env_file: ./data/.env
    volumes:
      - {{HOST_DATA_DIR}}:/app/data

  {{UPDATER_SERVICE}}:
    image: {{UPDATER_IMAGE}}
    container_name: {{UPDATER_SERVICE}}
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Read-write intentionally: update flows rewrite the image: line on
      # the main service via dockerops.SetServiceImage. A :ro mount blocks
      # the rewrite and breaks updates.
      - {{HOST_COMPOSE_FILE}}:/app/docker-compose.yml
      - {{HOST_DATA_DIR}}:/app/data
    environment:
      CLUBFOUNDRY_CLOUD_URL: {{CLOUD_URL}}
      CLUBFOUNDRY_COMPOSE_DIR: /app
      # Bind the API to loopback inside the host network namespace so the
      # main app can reach it via 127.0.0.1:3001 but it's not exposed on
      # public interfaces.
      CLUBFOUNDRY_UPDATER_ADDR: 127.0.0.1:3001
`

// envTemplate is the placeholder body of /app/data/.env. Empty —
// setup-wizard fills it. Comments document the canonical knobs so an
// operator who opens the file before completing the wizard sees what
// goes here.
const envTemplate = `# ClubFoundry — main app environment.
# Filled in by the setup wizard on first run (open http://<truenas>:3000).
# Manual edits also work; restart the stack after changing this file.
#
# CLM_TRUENAS_HOST=http://localhost
# CLM_TRUENAS_PORT=3000
# CLM_TRUENAS_API_KEY=
# CLM_INSTANCE_ID=
`
